### ISSUE TITLE
Support for additional shells

### ISSUE THREAD

**Issue by sourabhtk37** [dashohoxha/egpg#24]
There should be support for various other shells the user may use such as fish, zsh etc.
The shell can be identify via `getent passwd $LOGNAME | cut -d: -f7` and per shell config can be appended to the respective `rc` file.

**Comment by dashohoxha** [comment]
How many shells are there? Do we need to support all of them? Do they have a common denominator? For example are they all compatible with the good old **sh**, in the sense that a **sh** script will run in them without problems?

**Comment by sourabhtk37** [comment]
They are called `sh-compatible` shells. Majority of the shells are indeed `sh-compatible`. [Here](https://unix.stackexchange.com/a/145524) you can find more about it.

**Comment by dashohoxha** [comment]
But `fish` seems to be incompatible.

Given that `bash` is the most widely used shell, and the other shells are used only by tiny minorities, do you think it is worth to make these scripts compatible with all the other shells? Do you think it is even possible?

Another point is that these scripts have been developed and tested on Ubuntu, and maybe they work well on Debian too. In Ubuntu and Debian `bash` is the default shell. So, I think that maybe it is not worth supporting all the shells.

Anyway, thanks for raising this issue and for making research about it.

**Comment by sourabhtk37** [comment]
>Given that bash is the most widely used shell, and the other shells are used only by tiny minorities, do you think it is worth to make these scripts compatible with all the other shells? Do you think it is even possible?

Make sense. No issues on `fish` so far with egpg. Although there are sizable amount of `zsh` users, `ksh` would be considered minority.

>In Ubuntu and Debian bash is the default shell

The default `interactive` shell is `bash` and `/bin/sh` shell used for running scripts is `dash`. (Earlier it was `bash` in DebianLenny but changed to `dash` from Squeeze)

**Comment by dashohoxha** [comment]
> No issues on fish so far with egpg.

Maybe because each script starts with `#!/bin/bash` ?

**Comment by sourabhtk37** [comment]
Oh yeah :) My bad. Closing this then.

**Comment by dashohoxha** [comment]
> Oh yeah :) My bad.

My bad too, because I did't think about it right away. Maybe we should close this issue.
