### ISSUE TITLE
Update links on the website

### ISSUE THREAD

**Issue by dashohoxha** [dashohoxha/egpg#25]
Some url links on the new website refer to the old project or old website:
 - https://easygnupg.github.io/egpg/
 - https://github.com/EasyGnuPG/egpg/tree/gh-pages

They need to be updated.

**Comment by dashohoxha** [comment]
The wiki links need to be updated too, from  https://github.com/dashohoxha/egpg/wiki to https://github.com/EasyGnuPG/egpg/wiki.
Actually, https://github.com/dashohoxha should be replaced by https://github.com/EasyGnuPG everywhere.

**Comment by dashohoxha** [comment]
The same changes should be done on the branch `gnupg-2.2` as well.

**Comment by diveshuttam** [comment]
I have some university commitments today, I will pick this back tomorrow.

**Comment by dashohoxha** [comment]
> I have some university commitments today, I will pick this back tomorrow.

It is not urgent at all, take your time.
I assigned it to you since you already did the most part of this task, but any other student is welcome to give it a try, if the wish. It is not difficult at all.

What do you think @yugeshk ?

**Comment by yugeshk** [comment]
Nothing too complicated. I'm having dinner. Will do it in an hour

**Comment by diveshuttam** [comment]
@dashohoxha I tried updating the links in the wiki. Since wiki's are a separate git repository, I cloned the one corresponding to this project but couldn't find an option for creating a PR on the wiki. Also my fork doesn't have wiki pages. So I tried pushing directly to the wiki repo and it worked. Can you please review if they are correct.

The link for the wiki repo for this project is https://github.com/EasyGnuPG/egpg.wiki.git

**Comment by dashohoxha** [comment]
@diveshuttam thanks for fixing them. I did not think about fixing the wiki pages as well. And I didn't know that they were managed as a git repository.

> I tried pushing directly to the wiki repo and it worked.

Maybe because you have write access on the repository, or maybe because everyone can modify the wiki pages.

> Can you please review if they are correct.

I would prefer if @yugeshk checks them.
And if nothing else needs to be updated we can close this issue.

**Comment by diveshuttam** [comment]
@yugeshk, this issue is still pending can you have a look. If fine we can close this.

**Comment by yugeshk** [comment]
Yeah. I'm sorry for not having reported it - I've been following the wiki and man page for the past few days for learning Egpg. Everything seems fine to me!

**Comment by dashohoxha** [comment]
@diveshuttam you can close it. If there is any thing that needs to be fixed, we can fix it later.
