### ISSUE TITLE
Test and fix the branch gnupg-2.2

### ISSUE THREAD

**Issue by dashohoxha** [dashohoxha/egpg#27]
It should be adapted to work well with GnuPG-2.2

It should be useful to study the latest changes on GnuPG-2.2 (compared to GnuPG-2.1), and the latest version of the GnuPG docs, in order to check that maybe some of the things that EasyGnuPG tries to simplify are already simplified by GnuPG itself. This would make the code of EasyGnuPG lighter, less tricky, etc.

**Comment by dashohoxha** [comment]
@diveshuttam: If you have time to give this a try, I can give you some instructions on how to get started.

**Comment by diveshuttam** [comment]
Sure, but I have to complete an assignment today. I am free tomorrow (sunday), I'll give it a try then.

**Comment by dashohoxha** [comment]
In order to test and fix **egpg-2.2**, first of all we need to install and use **gnupg-2.2**. With the latest Ubuntu LTS (`ubuntu:18.04` or `ubuntu:bionic`) **gnupg-2.2** is actually the default version that is installed. Also with `debian:buster`.

So, we have to install and use `ubuntu:bionic` and/or `debian:buster`. This can be done on a VirtualBox machine, but it can also be done easily with a Docker container:
 - https://github.com/docker-scripts/ubuntu
 - https://github.com/docker-scripts/debian

After installing egpg-2.2 on this container, we can run the automated tests and see if some of the tests fail. Unfortunately these automated tests are not complete, so some manual testing is necessary too. Along the way, maybe the automated tests can be improved by adding more test cases.

**Comment by diveshuttam** [comment]
Hi @dashohoxha , I think I can start with this now. You seem to have done few commit towards this issue ([/EasyGnuPG/egpg-ds](/EasyGnuPG/egpg-ds)) What all needs to be done now?
As I understand,  you have created docker scripts for the purpose. I need to get them running on my laptop, try out the tests and do some manual testing. Anything else??

**Comment by dashohoxha** [comment]
Follow these steps:

 - [x] Build a test+dev environment by following the installation instructions on the README:
      + https://github.com/EasyGnuPG/egpg-ds#installation
 - [x] Create a man page for egpg-2.2 by cloning that for egpg-2.1:
      + https://easygnupg.github.io/egpg/gnupg-2.1/man/
 - [x] Create wiki pages for egpg-2.2 by cloning those for egpg-2.1:
      + https://github.com/easygnupg/egpg/wiki
 - [x] Follow manually all the examples in the man page and those on the wiki pages:
      + https://easygnupg.github.io/egpg/gnupg-2.1/man/#SIMPLE-EXAMPLE
      + https://easygnupg.github.io/egpg/gnupg-2.1/man/#ADVANCED-EXAMPLE
 - [x] Report any problems or anything that needs to be fixed, by creating issues.
 - [x] Try to fix these problems/bugs. I may also help you if you have difficulties with this.
 - [x] Run the automated tests.
 - [x] Report and try to fix any problems with automated tests. I may also help with this.

**Comment by dashohoxha** [comment]
Related to this: https://github.com/EasyGnuPG/pgpg/issues/74

**Comment by diveshuttam** [comment]
Closed in favor of #56
