### ISSUE TITLE
Improve bash scripting skills

### ISSUE THREAD

**Issue by dashohoxha** [dashohoxha/egpg#34]
Read these books/guides:
 - https://drive.google.com/file/d/1lMwE7lMEaWhayBcDUMZQP9Lun1wROAXN/view
 - https://en.wikibooks.org/wiki/Bash_Shell_Scripting

You will need these skills to read and understand the existing code of egpg.

**Comment by diveshuttam** [comment]
@dashohoxha 
I had already read the wiki page. Also I read a few chapters from the book earlier for fun.
Regarding the book, Do you want us to read all the parts or the part corresponding to bash scripting only (part 4)?

**Comment by dashohoxha** [comment]
Part 2 and 3 are optional, in my opinion. Part 1 is also important, but it has some basic stuff, that I think everybody knows.

**Comment by diveshuttam** [comment]
Cool.
I have read The Unix programming Environment recently. Though the book is old It covers quite a few central  ideas from part 1 and 2.Also, I think some of the topics in part 3 like package management can be useful. I will read them after doing part 4.
