### ISSUE TITLE
Can't run init after install

### ISSUE THREAD

**Issue by fsantiago07044** [dashohoxha/egpg#4]
Centos 7.2.x

Init produces:

 ~]# egpg init
Cannot find command file: /usr/lib/egpg/cmd\/init.sh

Seems like a typo somewhere adding an extra '\' in there.

**Comment by dashohoxha** [comment]
Yes, but it works for me (on Ubuntu 14.04), so maybe it is some problem with the environment or with the version of the shell. Here is the corresponding line:
https://github.com/dashohoxha/egpg/blob/master/src/egpg.sh#L101
Can you find out what is wrong with it and propose a fix?

**Comment by fsantiago07044** [comment]
Well, I took out the \ in my egpg.sh file (probably not the correct fix but for now) and now I receive:

# egpg init
which: no parcimonie in (/usr/lib64/qt-3.3/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/root/bin)
You should install parcimonie:
    sudo apt-get install parcimonie
[root@mail egpg]#

I did install from a centos / fedora project repo:

Parcimonie.sh which in turn also installed a torsocks as a dependency.

Apt-get doesn't apply to me. 

Also your wiki (or man) mentioned parcimonie is not required but this makes it seem like it is. 

Where to next? 

Sincerely,

Fabian Santiago

**Comment by dashohoxha** [comment]
Thanks for your patience :)
It is not perfect yet.
Comment out the part that requests parcimonie, and then try again.

**Comment by fsantiago07044** [comment]
hehe, where does that occur? I haven't found it yet. also, i'm not a 
dev....

**Comment by dashohoxha** [comment]
Sorry, I will fix it now, and you can get the latest version from GitHub.

**Comment by dashohoxha** [comment]
I did it: https://github.com/dashohoxha/egpg/commit/9b3b33575d7854548e56c7062e31002b4c89bcfc

**Comment by dashohoxha** [comment]
Fixed
