### ISSUE TITLE
Error in name of revocation certificate in gnupg-2.2 branch

### ISSUE THREAD

**Issue by diveshuttam** [dashohoxha/egpg#41]
The output of the following line has changed across gnupg 2.1 and gnupg 2.2

https://github.com/EasyGnuPG/egpg/blob/64859be7c88dc7498857d0ca7e46550c9e909537/src/auxiliary.sh#L69

This now(gnupg 2.2) lists the fingerprint of the sub key also which causes problem in the name of revocation certificate and others.

Refer https://github.com/EasyGnuPG/pgpg/issues/9

**Comment by dashohoxha** [comment]
Closed by #48
