### ISSUE TITLE
wiki entry innaccuracy

### ISSUE THREAD

**Issue by fsantiago07044** [dashohoxha/egpg#5]
I feel your wiki has a typo (but perhaps this is still a work in progress, not sure, so just wanted to mention it); you have written:

Try first:  egpg key gen
       or:  egpg key fetch
user@laptop:~$ egpg key-gen test@example.org "Test User"

'key-gen' doesn't work. i'll post more i come across.

**Comment by dashohoxha** [comment]
It is a typo (not a work in progress). Thanks for letting me know.
However I think that wiki should be editable by anybody. Next time maybe you can fix it yourself.

**Comment by dashohoxha** [comment]
Fixed
