### ISSUE TITLE
Tools to use for the GUI

### ISSUE THREAD

**Issue by dashohoxha** [dashohoxha/egpg#63]
I think that the best option is YAD:
 - http://www.thelinuxrain.com/articles/the-buttons-of-yad
 - http://smokey01.com/yad/
 - https://www.systutorials.com/docs/linux/man/1-yad/
 - https://developer.gnome.org/pango/stable/PangoMarkupFormat.html

If some interface cannot be constructed with `yad`, we can use GTK+Python directly:
 - https://python-gtk-3-tutorial.readthedocs.io/en/latest/index.html

**Comment by sourabhtk37** [comment]
Not going to use the python methods in pgpg for building it along with PyGobject for GUI?

**Comment by dashohoxha** [comment]
> Not going to use the python methods in pgpg for building it along with PyGobject for GUI?

I think that approach needs more time to be developed. Using bash+yad can be much faster.

That one can be the topic for another GSoC project (maybe continuing on top of `pgpg`, trying to build a fully Python based application).
