### ISSUE TITLE
pinentry seems to hang

### ISSUE THREAD

**Issue by fsantiago07044** [dashohoxha/egpg#7]
when running key gen, it asks for passphrase, accepts it, creates the key, and then pinentry appears asking for your key to unlock the secret key, but hangs there and doesn't accept any input. 

again, centos 7 with stock gpg and associated tools / deps installed.

**Comment by fsantiago07044** [comment]
but, if I ctrl-c out of pinentry, i see text output that indicates the process succeeded perhaps, ending in:

"Creating a revocation certificate."

not sure what comes next or if it's done at this point. if i do a key list -a, my key seems to be there.

**Comment by fsantiago07044** [comment]
all sign, seal, open, verify commands seem to work fine. 

revocation cert not present though as key revoke fails. so the key gen process DOES NOT complete successfully.

**Comment by dashohoxha** [comment]
Thanks @fsantiago07044 for testing it. This problem happens to me too, when I use pinentry-courses (instead pinentry-gtk-2), so it should be some pinentry configuration problem.

Right now I am writing some automatic testing scripts (to make sure that no regression bugs are introduced in the future), and this may take some time.

Next I am planning to try using Docker, similar to what letsencrypt does, to make sure that it is really platform independent (no worries anymore wether you run it on centos or ubuntu, etc.) However I am not sure whether it is going to work well. Pinentry may again be a challange.

**Comment by dashohoxha** [comment]
Closing in favour of #9
