### ISSUE TITLE
Some ideas for improvements

### ISSUE THREAD

**Issue by dashohoxha** [dashohoxha/egpg#74]
https://github.com/EasyGnuPG/egpg/pull/69#issuecomment-406882382

**Comment by diveshuttam** [comment]
closing this in favor of #91. issue #91 addresses the same cause. will create improvements after basic functionality is ready.
Will divide improvements to sub issues after we achieve a basic functionality.
Currently I am stacking all the improvement parts and TODO's in #91 only.
You can also discuss generic improvements that come to your mind in that issue only. Though for specific improvements I'll be creating a separate issues.
